import Head from "next/head";
import Home from "./home/Home";
import NavBar from "./components/NavBar";
import About_Me from "./about_me/About_Me";
import Projects from "./projects/Projects";
import Contact from "./contact/Contact";

export default function LandingPage() {
  return (
    <>
      <Head>
        <title>João Mota</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="z-10 absolute">
        <NavBar />
      </div>
      <main className="scroll-container">
        <Home />
        <About_Me />
        <Projects />
        <Contact />
      </main>
    </>
  );
}
